#!/usr/bin/env bash
set -Eeuo pipefail

# ============================================================
#  Simple IPsec Tunnel (IKEv2 + VTI) - Multi Tunnel Manager
#  Repo: https://github.com/ach1992/simple-ipsec-tunnel
#
#  Goal: GRE-like experience:
#   - Per-tunnel interface (vtiX)
#   - Local /30 tunnel IPs derived from PAIR CODE (10.X.Y)
#   - Multi tunnel
#   - Create / Edit (rename) / Status / Info / List / Delete
#   - COPY BLOCK to mirror settings on the other server
#
#  Tech:
#   - strongSwan (ipsec)
#   - Route-based IPsec: installpolicy=no + mark
#   - Linux VTI interface: ip link add vtiX type vti ... key MARK
#
#  Safety:
#   - secrets stored per tunnel with BEGIN/END markers (safe for same peer)
#   - robust rename: stops old service, removes old interface, removes old conn+secrets+conf
#   - sysctl persist: ip_forward + rp_filter disabled for tunnel interfaces
# ============================================================

APP_NAME="Simple IPsec Tunnel"
REPO_URL="https://github.com/ach1992/simple-ipsec-tunnel"

APP_DIR="/etc/simple-ipsec"
TUNNELS_DIR="$APP_DIR/tunnels.d"
SYSCTL_FILE="$APP_DIR/99-simple-ipsec.conf"

IPSEC_INCLUDE_DIR="/etc/ipsec.d/simple-ipsec"
IPSEC_CONF="/etc/ipsec.conf"
IPSEC_SECRETS="/etc/ipsec.secrets"
SECRETS_FILE="/etc/ipsec.d/simple-ipsec.secrets"

SERVICE_TEMPLATE="/etc/systemd/system/simple-ipsec@.service"
UP_HELPER="/usr/local/sbin/simple-ipsec-up"
DOWN_HELPER="/usr/local/sbin/simple-ipsec-down"

# Defaults
TUN_NAME_DEFAULT="vti0"
MTU_DEFAULT="1436"     # safe-ish default for ESP-in-UDP (NAT-T); adjust if needed
MARK_MIN=10
MARK_MAX=999999
ENABLE_FORWARDING_DEFAULT="yes"
DISABLE_RPFILTER_DEFAULT="yes"

# Colors
RED="\033[0;31m"; GRN="\033[0;32m"; YEL="\033[0;33m"; BLU="\033[0;34m"
MAG="\033[0;35m"; CYA="\033[0;36m"; WHT="\033[1;37m"; NC="\033[0m"
log()   { echo -e "${BLU}[INFO]${NC} $*"; }
ok()    { echo -e "${GRN}[OK]${NC} $*"; }
warn()  { echo -e "${YEL}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }
pause() { read -r -p "Press Enter to continue..." _; }

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    err "Run as root."
    exit 1
  fi
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }

require_cmds() {
  local missing=()
  for c in ip awk sed grep sysctl systemctl ping; do
    have_cmd "$c" || missing+=("$c")
  done
  have_cmd ipsec || missing+=("strongswan (ipsec)")
  if ((${#missing[@]})); then
    err "Missing required commands: ${missing[*]}"
    err "Debian/Ubuntu install:"
    err "  apt-get update && apt-get install -y strongswan iproute2 iputils-ping"
    exit 1
  fi
}

ensure_dirs() {
  mkdir -p "$APP_DIR" "$TUNNELS_DIR" "$IPSEC_INCLUDE_DIR"
  chmod 700 "$APP_DIR" "$TUNNELS_DIR" "$IPSEC_INCLUDE_DIR" || true
  touch "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"
}

# -----------------------
# Validation helpers
# -----------------------
is_ipv4() {
  local ip="$1"
  [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  local IFS=.
  read -r a b c d <<<"$ip"
  for o in "$a" "$b" "$c" "$d"; do
    [[ "$o" =~ ^[0-9]+$ ]] || return 1
    (( o >= 0 && o <= 255 )) || return 1
  done
  return 0
}

is_ifname() {
  local n="$1"
  [[ "$n" =~ ^[a-zA-Z0-9_.-]{1,15}$ ]] || return 1
  return 0
}

default_iface() {
  ip route 2>/dev/null | awk '/^default/{print $5; exit}'
}

get_iface_ip() {
  local iface="$1"
  ip -4 -o addr show dev "$iface" 2>/dev/null | awk '{print $4}' | head -n1 | cut -d/ -f1
}

# -----------------------
# Paths / naming
# -----------------------
conf_path_for() { echo "$TUNNELS_DIR/${1}.conf"; }
conn_name_for() { echo "simple-ipsec-${1}"; }
ipsec_conn_conf_for() { echo "$IPSEC_INCLUDE_DIR/${1}.conf"; }
service_for() { echo "simple-ipsec@${1}.service"; }

# -----------------------
# Tunnel list / choose
# -----------------------
list_tunnels() {
  shopt -s nullglob
  for f in "$TUNNELS_DIR"/*.conf; do
    basename "$f" .conf
  done
  shopt -u nullglob
}

choose_tunnel() {
  mapfile -t tunnels < <(list_tunnels)
  ((${#tunnels[@]})) || { err "No tunnels found."; return 1; }

  echo -e "${MAG}Available tunnels:${NC}"
  local i
  for i in "${!tunnels[@]}"; do
    printf "  %s) %s\n" "$((i+1))" "${tunnels[$i]}"
  done

  local choice
  while true; do
    read -r -p "Select tunnel [1-${#tunnels[@]}] (Enter=cancel): " choice || true
    [[ -n "${choice:-}" ]] || return 1
    if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice>=1 && choice<=${#tunnels[@]} )); then
      SELECTED_TUN="${tunnels[$((choice-1))]}"
      return 0
    fi
    err "Invalid selection."
  done
}

# -----------------------
# Read/Write per tunnel conf
# -----------------------
read_conf() {
  local f
  f="$(conf_path_for "$1")"
  [[ -f "$f" ]] || return 1
  # shellcheck disable=SC1090
  source "$f"
}

write_conf() {
  local tun="$1"
  local f
  f="$(conf_path_for "$tun")"
  cat >"$f" <<EOF
# Generated by simple-ipsec
ROLE="${ROLE}"
PAIR_CODE="${PAIR_CODE}"
TUN_NAME="${TUN_NAME}"
LOCAL_WAN_IP="${LOCAL_WAN_IP}"
REMOTE_WAN_IP="${REMOTE_WAN_IP}"
TUN_LOCAL_CIDR="${TUN_LOCAL_CIDR}"
TUN_REMOTE_IP="${TUN_REMOTE_IP}"
MARK="${MARK}"
MTU="${MTU}"
ENABLE_FORWARDING="${ENABLE_FORWARDING}"
DISABLE_RPFILTER="${DISABLE_RPFILTER}"
PSK="${PSK}"
EOF
  chmod 600 "$f"
}

# -----------------------
# Name handling (auto vtiN)
# -----------------------
name_taken_anywhere() {
  local name="$1"
  [[ -f "$(conf_path_for "$name")" ]] && return 0
  ip link show "$name" >/dev/null 2>&1 && return 0
  return 1
}

find_first_free_vti_name() {
  local base="${1:-vti}" i=0 cand
  while true; do
    cand="${base}${i}"
    if ! name_taken_anywhere "$cand"; then
      echo "$cand"; return 0
    fi
    i=$((i+1))
    (( i <= 4096 )) || return 1
  done
}

# -----------------------
# PAIR CODE -> /30
# -----------------------
generate_pair_code() { echo "10.$(( (RANDOM%254)+1 )).$(( (RANDOM%254)+1 ))"; }

parse_pair_code() {
  local pc="$1"
  [[ "$pc" =~ ^10\.([0-9]{1,3})\.([0-9]{1,3})$ ]] || return 1
  local x="${BASH_REMATCH[1]}" y="${BASH_REMATCH[2]}"
  (( x>=0 && x<=255 && y>=0 && y<=255 )) || return 1
  echo "$x $y"
}

recompute_tunnel_ips_from_pair() {
  local parsed rx ry
  parsed="$(parse_pair_code "$PAIR_CODE")" || { err "PAIR_CODE invalid."; return 1; }
  rx="${parsed% *}"; ry="${parsed#* }"

  if [[ "$ROLE" == "source" ]]; then
    TUN_LOCAL_CIDR="10.${rx}.${ry}.1/30"
    TUN_REMOTE_IP="10.${rx}.${ry}.2"
  else
    TUN_LOCAL_CIDR="10.${rx}.${ry}.2/30"
    TUN_REMOTE_IP="10.${rx}.${ry}.1"
  fi
}

# -----------------------
# COPY BLOCK
# -----------------------
print_copy_block() {
  local src dst
  if [[ "$ROLE" == "source" ]]; then
    src="$LOCAL_WAN_IP"; dst="$REMOTE_WAN_IP"
  else
    src="$REMOTE_WAN_IP"; dst="$LOCAL_WAN_IP"
  fi

  echo "----- SIMPLE_IPSEC_COPY_BLOCK -----"
  echo "PAIR_CODE=${PAIR_CODE}"
  echo "SOURCE_PUBLIC_IP=${src}"
  echo "DEST_PUBLIC_IP=${dst}"
  echo "TUN_NAME=${TUN_NAME}"
  echo "MARK=${MARK}"
  echo "MTU=${MTU}"
  echo "ENABLE_FORWARDING=${ENABLE_FORWARDING}"
  echo "DISABLE_RPFILTER=${DISABLE_RPFILTER}"
  echo "PSK=${PSK}"
  echo "----- END_COPY_BLOCK -----"
}

prompt_paste_copy_block() {
  echo -e "${CYA}Optional:${NC} Paste COPY BLOCK now (press Enter to skip)."
  echo -e "Finish paste by pressing ${WHT}Enter TWICE${NC} on empty lines."
  echo

  local first=""
  read -r -p "Paste first line (or just Enter to skip): " first || true
  [[ -n "${first:-}" ]] || return 0

  local lines=("$first") empty_count=0 line
  while true; do
    line=""
    read -r line || true
    if [[ -z "${line:-}" ]]; then
      empty_count=$((empty_count+1))
      (( empty_count>=2 )) && break
      continue
    fi
    empty_count=0
    lines+=("$line")
  done

  local kv key val
  for kv in "${lines[@]}"; do
    [[ "$kv" =~ ^[A-Z0-9_]+= ]] || continue
    key="${kv%%=*}"; val="${kv#*=}"
    case "$key" in
      PAIR_CODE) PAIR_CODE="$val" ;;
      SOURCE_PUBLIC_IP) PASTE_SOURCE_PUBLIC_IP="$val" ;;
      DEST_PUBLIC_IP)   PASTE_DEST_PUBLIC_IP="$val" ;;
      TUN_NAME) TUN_NAME="$val" ;;
      MARK) MARK="$val" ;;
      MTU) MTU="$val" ;;
      ENABLE_FORWARDING) ENABLE_FORWARDING="$val" ;;
      DISABLE_RPFILTER)  DISABLE_RPFILTER="$val" ;;
      PSK) PSK="$val" ;;
      *) : ;;
    esac
  done

  # validate lightly (hard validate later in prompts)
  [[ -z "${PAIR_CODE:-}" ]] || parse_pair_code "$PAIR_CODE" >/dev/null || { err "Bad PAIR_CODE in COPY BLOCK."; return 1; }
  [[ -z "${PASTE_SOURCE_PUBLIC_IP:-}" ]] || is_ipv4 "$PASTE_SOURCE_PUBLIC_IP" || { err "Bad SOURCE_PUBLIC_IP in COPY BLOCK."; return 1; }
  [[ -z "${PASTE_DEST_PUBLIC_IP:-}" ]] || is_ipv4 "$PASTE_DEST_PUBLIC_IP" || { err "Bad DEST_PUBLIC_IP in COPY BLOCK."; return 1; }
  [[ -z "${TUN_NAME:-}" ]] || is_ifname "$TUN_NAME" || { err "Bad TUN_NAME in COPY BLOCK."; return 1; }
  [[ -z "${MARK:-}" ]] || [[ "$MARK" =~ ^[0-9]+$ ]] || { err "Bad MARK in COPY BLOCK."; return 1; }
  [[ -z "${MTU:-}" ]] || [[ "$MTU" =~ ^[0-9]+$ ]] || { err "Bad MTU in COPY BLOCK."; return 1; }

  ok "COPY BLOCK parsed."
  return 0
}

# -----------------------
# Secrets (multi-safe)
# -----------------------
secrets_marker_begin() { echo "# BEGIN simple-ipsec:${1}"; }
secrets_marker_end()   { echo "# END simple-ipsec:${1}"; }

remove_secrets_block() {
  local tun="$1"
  [[ -f "$SECRETS_FILE" ]] || return 0
  sed -i "\|^# BEGIN simple-ipsec:${tun}\$|,\|^# END simple-ipsec:${tun}\$|d" "$SECRETS_FILE" || true
}

write_ipsec_secrets_block() {
  local tun="$1"
  remove_secrets_block "$tun"

  local begin end
  begin="$(secrets_marker_begin "$tun")"
  end="$(secrets_marker_end "$tun")"

  {
    echo "$begin"
    echo "# Peer pair: ${LOCAL_WAN_IP} <-> ${REMOTE_WAN_IP}"
    echo "${LOCAL_WAN_IP} ${REMOTE_WAN_IP} : PSK \"${PSK}\""
    echo "$end"
  } >> "$SECRETS_FILE"

  chmod 600 "$SECRETS_FILE"
}

# -----------------------
# strongSwan include hooks
# -----------------------
ensure_strongswan_includes() {
  # ipsec.conf include
  if [[ ! -f "$IPSEC_CONF" ]]; then
    err "$IPSEC_CONF not found. strongSwan installed?"
    return 1
  fi
  if ! grep -qE '^\s*include\s+/etc/ipsec\.d/simple-ipsec/\*\.conf\s*$' "$IPSEC_CONF"; then
    warn "Adding include line to $IPSEC_CONF (backup will be created)"
    cp -a "$IPSEC_CONF" "${IPSEC_CONF}.bak.$(date +%s)" || true
    printf "\n# added by simple-ipsec\ninclude /etc/ipsec.d/simple-ipsec/*.conf\n" >> "$IPSEC_CONF"
  fi

  # ipsec.secrets include
  if [[ ! -f "$IPSEC_SECRETS" ]]; then
    err "$IPSEC_SECRETS not found."
    return 1
  fi
  if ! grep -qE '^\s*include\s+/etc/ipsec\.d/simple-ipsec\.secrets\s*$' "$IPSEC_SECRETS"; then
    warn "Adding include line to $IPSEC_SECRETS (backup will be created)"
    cp -a "$IPSEC_SECRETS" "${IPSEC_SECRETS}.bak.$(date +%s)" || true
    printf "\n# added by simple-ipsec\ninclude /etc/ipsec.d/simple-ipsec.secrets\n" >> "$IPSEC_SECRETS"
  fi

  touch "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"
}

write_ipsec_conn_conf() {
  local tun="$1"
  local conn_name
  conn_name="$(conn_name_for "$tun")"

  cat >"$(ipsec_conn_conf_for "$tun")" <<EOF
# generated by simple-ipsec
conn ${conn_name}
  keyexchange=ikev2
  type=tunnel
  auto=start
  authby=psk

  left=${LOCAL_WAN_IP}
  right=${REMOTE_WAN_IP}

  # Route-based VTI
  mark=${MARK}
  installpolicy=no

  ike=aes256-sha256-modp2048!
  esp=aes256-sha256!

  dpdaction=restart
  dpddelay=30s
  keyingtries=%forever
EOF
  chmod 600 "$(ipsec_conn_conf_for "$tun")"
}

# -----------------------
# Sysctl persist (global)
# -----------------------
compute_global_forwarding_needed() {
  local t
  while IFS= read -r t; do
    read_conf "$t" || continue
    [[ "${ENABLE_FORWARDING:-no}" == "yes" ]] && { echo "yes"; return; }
  done < <(list_tunnels)
  echo "no"
}

compute_rpfilter_needed() {
  local t
  while IFS= read -r t; do
    read_conf "$t" || continue
    [[ "${DISABLE_RPFILTER:-no}" == "yes" ]] && { echo "yes"; return; }
  done < <(list_tunnels)
  echo "no"
}

write_sysctl_persist() {
  local forwarding_needed rp_needed
  forwarding_needed="$(compute_global_forwarding_needed)"
  rp_needed="$(compute_rpfilter_needed)"

  {
    echo "# Simple IPsec Tunnel sysctl (persist) - generated"
    echo "net.ipv4.ip_forward=$( [[ "$forwarding_needed" == "yes" ]] && echo 1 || echo 0 )"
    if [[ "$rp_needed" == "yes" ]]; then
      echo "net.ipv4.conf.all.rp_filter=0"
      echo "net.ipv4.conf.default.rp_filter=0"
      # also disable rp_filter per tunnel interface name
      local t
      while IFS= read -r t; do
        [[ -n "$t" ]] && echo "net.ipv4.conf.${t}.rp_filter=0"
      done < <(list_tunnels)
    fi
  } >"$SYSCTL_FILE"

  chmod 644 "$SYSCTL_FILE"
  sysctl --system >/dev/null 2>&1 || true
}

# -----------------------
# systemd template + helpers
# -----------------------
ensure_systemd_template() {
  cat >"$SERVICE_TEMPLATE" <<'EOF'
[Unit]
Description=Simple IPsec Tunnel - IPsec VTI (%i)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes

# Anti-hang: never wait forever
TimeoutStartSec=15
TimeoutStopSec=10

ExecStart=/usr/local/sbin/simple-ipsec-up %i
ExecStop=/usr/local/sbin/simple-ipsec-down %i

[Install]
WantedBy=multi-user.target
EOF

  cat >"$UP_HELPER" <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

APP_DIR="/etc/simple-ipsec"
TUNNELS_DIR="$APP_DIR/tunnels.d"
SYSCTL_FILE="$APP_DIR/99-simple-ipsec.conf"

tun="${1:-}"
[[ -n "${tun}" ]] || { echo "Usage: simple-ipsec-up <tunnel_name>" >&2; exit 2; }

CONF_FILE="$TUNNELS_DIR/${tun}.conf"
[[ -f "$CONF_FILE" ]] || { echo "Config not found: $CONF_FILE" >&2; exit 1; }
# shellcheck disable=SC1090
source "$CONF_FILE"

conn_name="simple-ipsec-${tun}"

apply_sysctl() {
  [[ -f "$SYSCTL_FILE" ]] && sysctl --system >/dev/null 2>&1 || true
  [[ "${ENABLE_FORWARDING:-no}" == "yes" ]] && sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true
  if [[ "${DISABLE_RPFILTER:-no}" == "yes" ]]; then
    sysctl -w net.ipv4.conf.all.rp_filter=0 >/dev/null 2>&1 || true
    sysctl -w net.ipv4.conf.default.rp_filter=0 >/dev/null 2>&1 || true
    sysctl -w "net.ipv4.conf.${TUN_NAME}.rp_filter=0" >/dev/null 2>&1 || true
  fi
}

ensure_vti() {
  if ! ip link show "${TUN_NAME}" >/dev/null 2>&1; then
    ip link add "${TUN_NAME}" type vti local "${LOCAL_WAN_IP}" remote "${REMOTE_WAN_IP}" key "${MARK}"
  fi
  ip link set "${TUN_NAME}" mtu "${MTU}" >/dev/null 2>&1 || true
  ip addr flush dev "${TUN_NAME}" >/dev/null 2>&1 || true
  ip addr add "${TUN_LOCAL_CIDR}" dev "${TUN_NAME}"
  ip link set "${TUN_NAME}" up
}

start_ipsec() {
  ipsec rereadsecrets >/dev/null 2>&1 || true
  ipsec reload >/dev/null 2>&1 || true

  # Anti-hang: don't block forever if peer isn't ready
  timeout 12 ipsec up "${conn_name}" >/dev/null 2>&1 || true
}


apply_sysctl
ensure_vti
start_ipsec
EOF

  cat >"$DOWN_HELPER" <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

APP_DIR="/etc/simple-ipsec"
TUNNELS_DIR="$APP_DIR/tunnels.d"

tun="${1:-}"
[[ -n "${tun}" ]] || { echo "Usage: simple-ipsec-down <tunnel_name>" >&2; exit 2; }

CONF_FILE="$TUNNELS_DIR/${tun}.conf"
[[ -f "$CONF_FILE" ]] || exit 0
# shellcheck disable=SC1090
source "$CONF_FILE"

conn_name="simple-ipsec-${tun}"

ipsec down "${conn_name}" >/dev/null 2>&1 || true
ip link set "${TUN_NAME}" down >/dev/null 2>&1 || true
ip link del "${TUN_NAME}" >/dev/null 2>&1 || true
EOF

  chmod +x "$UP_HELPER" "$DOWN_HELPER"
  systemctl daemon-reload
}

enable_service() { systemctl enable "$(service_for "$1")" >/dev/null 2>&1 || true; }
restart_service() { systemctl restart "$(service_for "$1")" >/dev/null 2>&1 || true; }
stop_disable_service() {
  systemctl stop "$(service_for "$1")" >/dev/null 2>&1 || true
  systemctl disable "$(service_for "$1")" >/dev/null 2>&1 || true
}

ipsec_reload_all() {
  ipsec rereadsecrets >/dev/null 2>&1 || true
  ipsec reload >/dev/null 2>&1 || true
}

# -----------------------
# Prompts (Create/Edit)
# -----------------------
prompt_role_create() {
  echo "Select server role:"
  echo "  1) Source (Iran)"
  echo "  2) Destination (Kharej)"
  local c
  while true; do
    read -r -p "Enter choice [1-2]: " c || true
    case "${c:-}" in
      1) ROLE="source"; break ;;
      2) ROLE="destination"; break ;;
      *) err "Invalid choice." ;;
    esac
  done
}

prompt_role_edit_keep() {
  echo "Current role: ${ROLE}"
  local c
  read -r -p "Change role? (1=Source, 2=Destination, Enter=keep): " c || true
  [[ -n "${c:-}" ]] || return 0
  case "$c" in
    1) ROLE="source" ;;
    2) ROLE="destination" ;;
    *) err "Invalid. Keeping role." ;;
  esac
}

prompt_tun_name_new() {
  local inp chosen
  read -r -p "VTI interface name [${TUN_NAME_DEFAULT}]: " inp || true
  inp="${inp:-$TUN_NAME_DEFAULT}"
  is_ifname "$inp" || { err "Invalid interface name."; return 1; }

  if ! name_taken_anywhere "$inp"; then
    TUN_NAME="$inp"; return 0
  fi

  if [[ "$inp" == "vti" || "$inp" =~ ^vti[0-9]+$ ]]; then
    chosen="$(find_first_free_vti_name vti)" || { err "No free vtiN available."; return 1; }
    warn "Name taken. Auto-selected: $chosen"
    TUN_NAME="$chosen"; return 0
  fi

  err "Name '$inp' is already taken."
  return 1
}

prompt_tun_name_edit_keep_or_rename() {
  local inp
  read -r -p "VTI interface name [${TUN_NAME}] (Enter=keep): " inp || true
  inp="${inp:-$TUN_NAME}"
  is_ifname "$inp" || { err "Invalid interface name."; return 1; }

  if [[ "$inp" != "$TUN_NAME" ]]; then
    if name_taken_anywhere "$inp"; then
      err "Name '$inp' is already taken."
      return 1
    fi
  fi

  TUN_NAME="$inp"
  return 0
}

prompt_local_wan_ip() {
  local inp def_if def_ip
  def_if="$(default_iface || true)"
  def_ip=""
  [[ -n "${def_if:-}" ]] && def_ip="$(get_iface_ip "$def_if" || true)"

  if [[ -n "${LOCAL_WAN_IP:-}" ]]; then
    read -r -p "Local public IPv4 [${LOCAL_WAN_IP}]: " inp || true
    inp="${inp:-$LOCAL_WAN_IP}"
  elif [[ -n "${def_ip:-}" ]]; then
    read -r -p "Local public IPv4 (detected: ${def_ip}) [${def_ip}]: " inp || true
    inp="${inp:-$def_ip}"
  else
    read -r -p "Local public IPv4: " inp || true
  fi

  is_ipv4 "${inp:-}" || { err "Invalid IPv4."; return 1; }
  LOCAL_WAN_IP="$inp"
}

prompt_remote_wan_ip() {
  local inp
  read -r -p "Remote public IPv4 [${REMOTE_WAN_IP:-}]: " inp || true
  inp="${inp:-${REMOTE_WAN_IP:-}}"
  is_ipv4 "${inp:-}" || { err "Invalid IPv4."; return 1; }
  REMOTE_WAN_IP="$inp"
}

prompt_pair_code_create() {
  echo "PAIR CODE format: 10.X.Y"
  local inp
  read -r -p "PAIR CODE [auto]: " inp || true
  if [[ -z "${inp:-}" ]]; then
    PAIR_CODE="$(generate_pair_code)"
    ok "Generated PAIR CODE: $PAIR_CODE"
  else
    parse_pair_code "$inp" >/dev/null || { err "Invalid PAIR CODE."; return 1; }
    PAIR_CODE="$inp"
  fi
}

prompt_pair_code_edit_keep() {
  echo "PAIR CODE format: 10.X.Y"
  local inp
  read -r -p "PAIR CODE [${PAIR_CODE}] (Enter=keep): " inp || true
  inp="${inp:-$PAIR_CODE}"
  parse_pair_code "$inp" >/dev/null || { err "Invalid PAIR CODE."; return 1; }
  PAIR_CODE="$inp"
}

prompt_mark_keep() {
  local inp
  [[ -n "${MARK:-}" ]] || MARK=$(( (RANDOM % (MARK_MAX - MARK_MIN + 1)) + MARK_MIN ))
  read -r -p "MARK (VTI key/mark) [${MARK}] (Enter=keep): " inp || true
  inp="${inp:-$MARK}"
  [[ "$inp" =~ ^[0-9]+$ ]] && (( inp>=1 && inp<=2147483647 )) || { err "Invalid MARK."; return 1; }
  MARK="$inp"
}

prompt_mtu_keep() {
  local inp
  [[ -n "${MTU:-}" ]] || MTU="$MTU_DEFAULT"
  read -r -p "MTU [${MTU}] (Enter=keep): " inp || true
  inp="${inp:-$MTU}"
  [[ "$inp" =~ ^[0-9]+$ ]] && (( inp>=1200 && inp<=9000 )) || { err "Invalid MTU."; return 1; }
  MTU="$inp"
}

prompt_tuning_keep() {
  local inp
  [[ -n "${ENABLE_FORWARDING:-}" ]] || ENABLE_FORWARDING="$ENABLE_FORWARDING_DEFAULT"
  [[ -n "${DISABLE_RPFILTER:-}" ]] || DISABLE_RPFILTER="$DISABLE_RPFILTER_DEFAULT"

  read -r -p "Enable IPv4 forwarding? [${ENABLE_FORWARDING}] (yes/no, Enter=keep): " inp || true
  inp="${inp:-$ENABLE_FORWARDING}"
  [[ "$inp" == "yes" || "$inp" == "no" ]] || { err "Invalid value."; return 1; }
  ENABLE_FORWARDING="$inp"

  read -r -p "Disable rp_filter? [${DISABLE_RPFILTER}] (yes/no, Enter=keep): " inp || true
  inp="${inp:-$DISABLE_RPFILTER}"
  [[ "$inp" == "yes" || "$inp" == "no" ]] || { err "Invalid value."; return 1; }
  DISABLE_RPFILTER="$inp"
}

prompt_psk_keep_or_set() {
  local inp
  if [[ -z "${PSK:-}" ]]; then
    read -r -p "PSK (shared secret) [auto-generate]: " inp || true
    if [[ -z "${inp:-}" ]]; then
      PSK="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32 || true)"
      ok "Generated PSK."
    else
      PSK="$inp"
    fi
  else
    read -r -p "PSK [hidden] (Enter=keep, type new to change): " inp || true
    [[ -n "${inp:-}" ]] && PSK="$inp"
  fi
  ((${#PSK} >= 8)) || { err "PSK too short."; return 1; }
}

# -----------------------
# Core apply/remove operations
# -----------------------
apply_tunnel_files_and_service() {
  local tun="$1"

  write_conf "$tun"
  write_ipsec_conn_conf "$tun"
  write_ipsec_secrets_block "$tun"
  write_sysctl_persist

  enable_service "$tun"
  timeout 15 systemctl restart "$(service_for "$tun")" >/dev/null 2>&1 || true

  ipsec_reload_all
}

remove_tunnel_everything() {
  local tun="$1"
  # read to get interface name etc (usually equal to tun)
  read_conf "$tun" || true

  stop_disable_service "$tun"

  # remove VTI interface (best-effort)
  ip link set "$tun" down >/dev/null 2>&1 || true
  ip link del "$tun" >/dev/null 2>&1 || true

  # remove strongSwan conn + secrets block
  rm -f "$(ipsec_conn_conf_for "$tun")" >/dev/null 2>&1 || true
  remove_secrets_block "$tun"

  # remove config
  rm -f "$(conf_path_for "$tun")" >/dev/null 2>&1 || true

  write_sysctl_persist
  ipsec_reload_all
}

# -----------------------
# Actions (menu)
# -----------------------
do_list() {
  echo -e "${MAG}===== Tunnels =====${NC}"
  local found="no" t
  while IFS= read -r t; do
    [[ -n "$t" ]] && { echo " - $t"; found="yes"; }
  done < <(list_tunnels)
  [[ "$found" == "yes" ]] || warn "No tunnels configured."
}

do_info() {
  choose_tunnel || return
  local tun="$SELECTED_TUN"
  read_conf "$tun" || { err "Config not found."; return; }

  echo -e "${MAG}===== IPsec(VTI) Info: ${tun} =====${NC}"
  echo "Role:                $ROLE"
  echo "Pair code:           $PAIR_CODE"
  echo "Tunnel name:         $TUN_NAME"
  echo "Local public IP:     $LOCAL_WAN_IP"
  echo "Remote public IP:    $REMOTE_WAN_IP"
  echo "Local tunnel CIDR:   $TUN_LOCAL_CIDR"
  echo "Remote tunnel IP:    $TUN_REMOTE_IP"
  echo "MARK:                $MARK"
  echo "MTU:                 $MTU"
  echo "IPv4 forwarding:     $ENABLE_FORWARDING"
  echo "rp_filter disabled:  $DISABLE_RPFILTER"
  echo "Config file:         $(conf_path_for "$tun")"
  echo "IPsec conn file:     $(ipsec_conn_conf_for "$tun")"
  echo

  echo -e "${CYA}COPY BLOCK (paste on the other server):${NC}"
  warn "COPY BLOCK includes PSK. Keep it private."
  print_copy_block
}

do_status_one() {
  choose_tunnel || return
  local tun="$SELECTED_TUN"
  read_conf "$tun" || { err "Config not found."; return; }

  echo -e "${MAG}===== Status: ${tun} =====${NC}"
  echo -e "${WHT}Service:${NC}"
  systemctl --no-pager --full status "$(service_for "$tun")" || true
  echo

  echo -e "${WHT}Interface:${NC}"
  ip -d link show "$tun" 2>/dev/null || { warn "Interface '$tun' not found (service may be down)."; }
  ip -4 addr show dev "$tun" 2>/dev/null || true
  echo

  echo -e "${WHT}Counters:${NC}"
  ip -s link show "$tun" 2>/dev/null || true
  echo

  echo -e "${WHT}IPsec status (top):${NC}"
  ipsec statusall | sed -n '1,80p' || true
  echo

  echo -e "${WHT}Ping remote tunnel IP:${NC} ${TUN_REMOTE_IP}"
  if ping -c 3 -W 2 "$TUN_REMOTE_IP" >/dev/null 2>&1; then
    ok "Ping OK."
  else
    warn "Ping failed. Check: MTU, both sides same PAIR_CODE/MARK/PSK, rp_filter=0, and IPsec is UP."
  fi
}

do_status_all() {
  echo -e "${MAG}===== Status: ALL Tunnels =====${NC}"
  local t any="no"
  while IFS= read -r t; do
    [[ -n "$t" ]] || continue
    any="yes"
    echo -e "${CYA}--- ${t} ---${NC}"
    if read_conf "$t"; then
      systemctl is-active --quiet "$(service_for "$t")" && echo "Service: active" || echo "Service: inactive"
      ip link show "$t" >/dev/null 2>&1 && echo "Interface: present" || echo "Interface: missing"
      echo "Tunnel IP: ${TUN_LOCAL_CIDR} -> ${TUN_REMOTE_IP}"
    else
      echo "Config: missing"
    fi
    echo
  done < <(list_tunnels)

  [[ "$any" == "yes" ]] || warn "No tunnels configured."
}

do_create() {
  log "Create NEW IPsec(VTI) tunnel"
  echo

  # defaults
  ROLE=""
  TUN_NAME=""
  LOCAL_WAN_IP=""
  REMOTE_WAN_IP=""
  PAIR_CODE=""
  MARK=""
  MTU="$MTU_DEFAULT"
  ENABLE_FORWARDING="$ENABLE_FORWARDING_DEFAULT"
  DISABLE_RPFILTER="$DISABLE_RPFILTER_DEFAULT"
  PSK=""
  PASTE_SOURCE_PUBLIC_IP=""
  PASTE_DEST_PUBLIC_IP=""

  prompt_role_create
  echo

  # optional paste block
  prompt_paste_copy_block || { err "COPY BLOCK parse failed."; return; }
  echo

  # name
  prompt_tun_name_new || return

  # if COPY BLOCK provided public IPs, map them based on role
  if [[ -n "${PASTE_SOURCE_PUBLIC_IP:-}" && -n "${PASTE_DEST_PUBLIC_IP:-}" ]]; then
    if [[ "$ROLE" == "source" ]]; then
      LOCAL_WAN_IP="$PASTE_SOURCE_PUBLIC_IP"
      REMOTE_WAN_IP="$PASTE_DEST_PUBLIC_IP"
    else
      LOCAL_WAN_IP="$PASTE_DEST_PUBLIC_IP"
      REMOTE_WAN_IP="$PASTE_SOURCE_PUBLIC_IP"
    fi
    ok "Public IPs imported from COPY BLOCK."
  fi

  prompt_local_wan_ip || return
  prompt_remote_wan_ip || return

  # pair code
  if [[ -z "${PAIR_CODE:-}" ]]; then
    prompt_pair_code_create || return
  else
    # already pasted
    parse_pair_code "$PAIR_CODE" >/dev/null || { err "Invalid PAIR_CODE from COPY BLOCK."; return; }
  fi
  recompute_tunnel_ips_from_pair || return

  # mark / mtu / sysctl / psk
  prompt_mark_keep || return
  prompt_mtu_keep || return
  prompt_tuning_keep || return
  prompt_psk_keep_or_set || return

  ensure_strongswan_includes
  ensure_systemd_template

  # FINAL apply
  apply_tunnel_files_and_service "$TUN_NAME"

  ok "Tunnel '${TUN_NAME}' created & applied."
  echo
  echo -e "${GRN}Tunnel addressing:${NC}"
  echo "  PAIR_CODE:         ${PAIR_CODE}"
  echo "  Local CIDR:        ${TUN_LOCAL_CIDR}"
  echo "  Remote tunnel IP:  ${TUN_REMOTE_IP}"
  echo
  echo -e "${CYA}COPY BLOCK (paste on the other server):${NC}"
  warn "COPY BLOCK includes PSK. Keep it private."
  print_copy_block
}

do_edit() {
  choose_tunnel || return
  local old_tun="$SELECTED_TUN"

  read_conf "$old_tun" || { err "Config not found for: $old_tun"; return; }

  log "Edit tunnel: $old_tun"
  warn "Press Enter to keep existing values."
  echo

  # Keep a snapshot
  local old_role="$ROLE"
  local old_pair="$PAIR_CODE"
  local old_local_wan="$LOCAL_WAN_IP"
  local old_remote_wan="$REMOTE_WAN_IP"
  local old_mark="$MARK"
  local old_mtu="$MTU"
  local old_fwd="$ENABLE_FORWARDING"
  local old_rpf="$DISABLE_RPFILTER"
  local old_psk="$PSK"
  local old_name="$TUN_NAME" # normally equals old_tun

  prompt_role_edit_keep
  prompt_pair_code_edit_keep || { ROLE="$old_role"; return; }
  recompute_tunnel_ips_from_pair || { ROLE="$old_role"; PAIR_CODE="$old_pair"; return; }

  prompt_tun_name_edit_keep_or_rename || { ROLE="$old_role"; PAIR_CODE="$old_pair"; return; }
  prompt_local_wan_ip || { ROLE="$old_role"; return; }
  prompt_remote_wan_ip || { ROLE="$old_role"; return; }

  prompt_mark_keep || { MARK="$old_mark"; return; }
  prompt_mtu_keep || { MTU="$old_mtu"; return; }
  prompt_tuning_keep || { ENABLE_FORWARDING="$old_fwd"; DISABLE_RPFILTER="$old_rpf"; return; }
  prompt_psk_keep_or_set || { PSK="$old_psk"; return; }

  ensure_strongswan_includes
  ensure_systemd_template

  # If renamed, we must remove old artifacts safely first
  if [[ "$TUN_NAME" != "$old_tun" ]]; then
    warn "Renaming tunnel: ${old_tun} -> ${TUN_NAME}"
    # stop old service + remove old interface + old conn + old secrets + old conf
    stop_disable_service "$old_tun"
    ip link set "$old_tun" down >/dev/null 2>&1 || true
    ip link del "$old_tun" >/dev/null 2>&1 || true
    rm -f "$(ipsec_conn_conf_for "$old_tun")" >/dev/null 2>&1 || true
    remove_secrets_block "$old_tun"
    rm -f "$(conf_path_for "$old_tun")" >/dev/null 2>&1 || true
  else
    # same name: just restart later
    stop_disable_service "$old_tun" >/dev/null 2>&1 || true
  fi

  # apply new artifacts under new name
  apply_tunnel_files_and_service "$TUN_NAME"

  ok "Tunnel updated & applied: ${TUN_NAME}"
  echo
  echo -e "${CYA}COPY BLOCK (paste on the other server):${NC}"
  warn "COPY BLOCK includes PSK. Keep it private."
  print_copy_block
}

do_delete() {
  choose_tunnel || return
  local tun="$SELECTED_TUN"

  warn "Delete tunnel '$tun' (service + interface + ipsec conn + secrets block + config)."
  local yn
  read -r -p "Are you sure? [y/N]: " yn || true
  [[ "${yn:-N}" =~ ^([yY])$ ]] || { log "Canceled."; return; }

  remove_tunnel_everything "$tun"
  ok "Deleted tunnel: $tun"
}

# -----------------------
# Banner / menu
# -----------------------
banner() {
  echo -e "${MAG}========================================${NC}"
  echo -e "${WHT}  ${APP_NAME}${NC}  ${CYA}(IKEv2 + VTI | Multi Tunnel)${NC}"
  echo -e "${YEL}  Repo:${NC} ${BLU}${REPO_URL}${NC}"
  echo -e "${MAG}========================================${NC}"
}

menu() {
  while true; do
    clear || true
    banner
    echo -e "${CYA}1)${NC} Create tunnel (new)"
    echo -e "${CYA}2)${NC} Edit tunnel"
    echo -e "${CYA}3)${NC} Status (one tunnel)"
    echo -e "${CYA}4)${NC} Status (ALL tunnels)"
    echo -e "${CYA}5)${NC} Info / COPY BLOCK (one tunnel)"
    echo -e "${CYA}6)${NC} List tunnels"
    echo -e "${CYA}7)${NC} Delete tunnel"
    echo -e "${CYA}0)${NC} Exit"
    echo -e "${MAG}----------------------------------------${NC}"
    local choice
    read -r -p "Select an option [0-7]: " choice || true
    case "${choice:-}" in
      1) do_create; pause ;;
      2) do_edit; pause ;;
      3) do_status_one; pause ;;
      4) do_status_all; pause ;;
      5) do_info; pause ;;
      6) do_list; pause ;;
      7) do_delete; pause ;;
      0) exit 0 ;;
      *) err "Invalid selection."; pause ;;
    esac
  done
}

main() {
  require_root
  require_cmds
  ensure_dirs
  ensure_strongswan_includes
  ensure_systemd_template
  write_sysctl_persist
  menu
}

main "$@"
